config/routes.rb
Opentable::Application.routes.draw do

  resources :restaurants do
    resources :reservations
  end

  resources :sessions, :only => [:new, :create, :destroy]

  resources :users, :except => [:index]

  

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user

	# before_create :validate_reservation

	# def validate_reservation
	# 	reservation_time = reservation.reservation_time.to_s
	# 	reserved_seats = Restarants.find[:id].reservations
	# end

	before_create :check_availability
	
	private

	def check_availability
		reservations = Restaurant.find(restaurant_id).reservations.where('reservation_time', reservation_time.to_s)
		total_bookings = reservations.inject(0) { |sum, reservation| sum + reservation.party_size }
		if (Restaurant.find(restaurant_id).max_seats - total_bookings) < party_size
			return false
		end
	end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, :phone_number, :summary, :address, :city, :province, :postal_code, :website, presence: true
	validates :email, format: { with: /(\S+)@(\S+)/ }, presence: true
	validates :max_seats, numericality: true

	has_many :reservations, :dependent => :destroy
	has_many :users, :through => :reservations
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, :last_name, :password_digest, :phone_number, presence: true
	validates :email, format: { with: /(\S+)@(\S+)/ }, presence: true

	has_secure_password
	validates_presence_of :password, :on => :create

	has_many :reservations
	has_many :restaurants, :through => :reservations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_filter :ensure_logged_in, :only => [:new, :edit, :destroy]
	before_filter :load_restaurant

	def show
	end

	def new
		@reservation = Reservation.new
	end

	def create
				@reservation = @restaurant.reservations.build(reservation_params)
				@reservation.user_id = current_user.id
			if @reservation.save
				UserMailer.reservation_confirmation(@reservation).deliver
				flash[:notice] = "Your reservation at #{@reservation.restaurant.name} is confirmed"
				redirect_to user_path(current_user.id)
			else
				flash[:notice] = "No Space, Please Come Again!"
				redirect_to restaurant_path(params[:restaurant_id])
			end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private

	def load_restaurant
		@restaurant = Restaurant.find(params[:restaurant_id])
	end

	def reservation_params
		params.require(:reservation).permit(:user_id, :restaurant_id, :reservation_time, :end_time, :party_size)
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_filter :ensure_logged_in, :only => [:edit, :new, :destroy]

	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		@reservation = @restaurant.reservations.build
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.update(restaurant_params)
			flash[:notice] = "restaurant updated!"
			redirect_to @restaurant
		else
			render :edit
		end		
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
		if @restaurant.save
			flash[:notice] = "Restaurant created!"
			redirect_to @restaurant
		else
			render :new
		end
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		flash[:alert] = "Restaurant deleted!"
		redirect_to restaurants_path
	end

private

	def restaurant_params
		params.require(:restaurant).permit(:name, :phone_number, :summary, :address, :city, :province, :postal_code, :email, :website, :max_seats)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to restaurants_url, :notice => "Logged in!"
		else
			flash.now[:alert] = "Invalid email or password"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to restaurants_path, :notice => "Successfully logged out"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	# def index
	# end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "#{@user.first_name}'s profile successfully updated"
			redirect_to @user
		else
			render :edit
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			UserMailer.welcome_email(@user).deliver
			flash[:notice] = "#{@user.first_name}, Welcome to Seat Yourself! Bon Appetit!"
			redirect_to @user
		else
			render :new
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:alert] = "User deleted!"
		redirect_to restaurants_path
	end

private
	
	def user_params
		params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :user_type, :email, :phone_number)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav>
	<br/>
	<% if current_user %>
		Signed in as <%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user) %> | 
		<%= link_to "Log out", session_path("current"), :method => :delete %> |
		<% else %>
			<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %> | 
	<% end %>
		<%= link_to "Restaurants", restaurants_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opentable</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/flash" %>

<%= yield %>

<%= render "layouts/nav" %>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
	<fieldset>
		<ul>
			<li>
				<%= f.label :name %>
				<%= f.text_field :name %>
			</li>
			<li>
				<%= f.label :summary %>
				<%= f.text_area :summary, cols: 40, rows: 7 %>
			</li>
			<li>
				<%= f.label :address %>
				<%= f.text_field :address %>
			</li>
			<li>
				<%= f.label :city %>
				<%= f.text_field :city %>
			</li>
			<li>
				<%= f.label :province %>
				<%= f.text_field :province %>
			</li>
			<li>
				<%= f.label :postal_code %>
				<%= f.text_field :postal_code %>
			</li>
			<li>
				<%= f.label :phone_number %>
				<%= f.telephone_field :phone_number %>
			</li>
			<li>
				<%= f.label :email %>
				<%= f.email_field :email %>
			</li>
			<li>
				<%= f.label :website %>
				<%= f.url_field :website %>
			</li>
			<li>
				<%= f.label :max_seats %>
				<%= f.number_field :max_seats %>
			</li>
		</ul>
	</fieldset>
	<p>
		<%= f.submit %> | 
		<%= link_to "Cancel", restaurant_path(@restaurant) %>
	</p>
<% end %>

app/views/restaurants/_reservation_form.html.erb
<h4>Make a Reservation</h4>

	<%= form_for([@restaurant, @reservation]) do |f| %>
		<fieldset>
			<legend>Select Reservation Date and Time <em>(All reservations are set for 1 hours)</em></legend>
			<%= f.datetime_select :reservation_time, :start_year => Time.zone.now.year, :end_year => Time.zone.now.year + 2, :use_short_month => true, ampm: true, minute_step: 60, start_hour: 8, end_hour: 21 %>
		</fieldset>
		<p>
			<%= f.label :party_size %>
			<%= f.select :party_size, (1..20) %>
		</p>
		<p>
			<%= f.submit %> | 
			<%= link_to "Cancel", restaurant_path(@restaurant) %>
		</p>
	<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Where to Dine?</h1>

<% @restaurants.each do |restaurant| %>
<article class="restaurant">
	<h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
	<h4>Summary</h4>
	<p><%= restaurant.summary %></p>
	<h4>Contact</h4>
	<p><%= restaurant.address %>, <%=restaurant.city %>, <%= restaurant.province %>, <%= restaurant.postal_code %></p>
	<p><%= restaurant.phone_number %></p>
</article>
<% end %>

app/views/restaurants/new.html.erb
<h1>Create New Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<div id="restaurant_details">
	<h2>Summary</h2>
	<p><%= @restaurant.summary %></p>
	<p><strong>Maximum Capacity: </strong><%=@restaurant.max_seats %></p>
	<h2>How to find us!</h2>
	<p><strong>Address: </strong>
		<%= @restaurant.address %>
		<%= @restaurant.city %>, <%= @restaurant.province %>
		<%= @restaurant.postal_code %>		
	</p>
	<p><strong>Phone Number: </strong><%= @restaurant.phone_number %></p>
	<p><strong>Email: </strong><a href="mailto:<%= @restaurant.email %>?Subject=Seat%20Yourself%20Customer">Send an email</a></p>
	<p><strong>Website: </strong><a href="<%= @restaurant.website %>" target="_blank">Visit their website</a></p>
</div>

<%= link_to "Edit", edit_restaurant_path(@restaurant) %> | 
<%= link_to 'Delete',@restaurant, method: :delete, data: { confirm: 'Are you sure?' } %><br/>

<% if current_user.nil? %>
	<%= link_to 'Please log in to make a reservation', new_session_path %>
<% else %>
	<%= render 'reservation_form' %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
	<p id="alert"><%= flash[:alert] %></p>
<% end %>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
	<fieldset>
		<ul>
			<li>
				<%= f.label :first_name%>
				<%= f.text_field :first_name, autofocus: true  %>
				<%= f.label :last_name %>
				<%= f.text_field :last_name %>
			</li>
			<li>
				<%= f.label :email %>
				<%= f.email_field :email %>
			</li>
			<li>
				<%= f.label :password %>
				<%= f.password_field :password %>
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			</li>
			<li>
				<%= f.label :phone_number %>
				<%= f.telephone_field :phone_number %>
			</li>
		</ul>
	</fieldset>
	<p>
		<%= f.submit %> | 
		<%= link_to "Cancel", restaurants_path %>
	</p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.first_name %>'s Profile</h1>

<%= render 'user_form' %>

app/views/users/new.html.erb
<h1>New User Page</h1>

<%= render 'user_form' %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%=@user.last_name %>'s Profile Page</h1>

<h2>My upcoming reservations</h2>
	<table border='1'>
	<tr>
		<th>Reservation ID</th>
		<th>Restaurant</th>
		<th>Reseration Date/Time</th>
		<th>Party Size</th>
	</tr>
	<% @user.reservations.each do |reservation| %>
		<% if reservation.reservation_time.future? %>
			<tr>
				<td><%= reservation.id %></td>
				<td><%= link_to reservation.restaurant.name, restaurant_path(reservation.restaurant_id) %></td>
				<td><%= reservation.reservation_time.strftime("%b %d, %Y @ %I:%M %P") %></td>
				<td><%= reservation.party_size %></td>
			</tr>
		<% end %>
	<% end %>
	</table>